{
    'name': "Tour Management",

    'summary': "",

    'description': "Tour and Travel management odoo module helps to manage contracts with all your suppliers with your accommodation, transportation, restaurants, guides and other logistical requirements.",

    'author': "GeeksDigital",
    'website': "",
    'category': '',
    'version': '0.1',
    'depends': ['base', 'mail', 'hr', 'contacts', 'account'],
    'data': [
        "security/ir.model.access.csv",
        "views/sequences.xml",
         "views/place.xml",
        'views/transfer_excursions_view.xml',
        'views/job_card_view.xml',
        "views/base_menu.xml",
        "views/tour_reservation.xml",
        "views/visa_documentation_list.xml",
        "views/accommodation.xml",
        "views/room_type.xml",
        "views/meal.xml",
        "views/payment_policy.xml",
        "views/flight_name.xml",
        "views/transport.xml",
        "views/travel_class.xml",
        "views/travel_info.xml",
        "views/tour_details.xml",
        "views/tour_inquiry.xml",
        "views/tour_itinerary.xml",
        "views/booking_info.xml",
        "views/service.xml",
        "views/extra_service.xml",
        "views/ferry.xml",
        "views/flight.xml",
        "views/tour_visa.xml",
        "views/insurance.xml",
        "views/booking_accommodation.xml",
        "views/tour_passport_documentation.xml",
        "views/agent_commission.xml",
        "views/day_sheet.xml",
        "views/sub_agent_view.xml",
        "views/guide_view.xml",
        "views/driver_view.xml",
        "views/other_contact_view.xml",
        "views/tour_consultant_view.xml",
        "views/all_contact_view.xml",
        "views/agent_views.xml",
        "views/tour_booking.xml"
    ],
    'assets': {
    },
    'demo': [
    ],
    'application': True,

}
